name: lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: php -l
        run: php -l wp-stateless-azure.php
